In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

print("sucessefully imported")

sucessefully imported

In [14]:
data = {
    "Study_Hours": [1,2,3,4,5,6,7,8,9,10],
    "Exam_Score": [35,40,45,50,55,60,65,70,75,80]
}

df = pd.DataFrame(data)
df

   Study_Hours  Exam_Score
0            1          35
1            2          40
2            3          45
3            4          50
4            5          55
5            6          60
6            7          65
7            8          70
8            9          75
9           10          80

In [16]:
X = df[["Study_Hours"]]
y = df["Exam_Score"]

X

   Study_Hours
0            1
1            2
2            3
3            4
4            5
5            6
6            7
7            8
8            9
9           10

In [19]:
y

0    35
1    40
2    45
3    50
4    55
5    60
6    65
7    70
8    75
9    80
Name: Exam_Score, dtype: int64

In [20]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
        test_size = 0.2,
        random_state = 42
)

In [21]:
#create model

In [22]:
en_r = ElasticNet(alpha = 0.1,l1_ratio = 0.5)

In [23]:
#train model

In [25]:
en_r.fit(X_train,y_train);

In [35]:
print("\nCoefficent : ",en_r.coef_[0])

Coefficent :  4.958904109589041

In [39]:
pred = en_r.predict(X_test)

In [42]:
print("\nMSE : ",mean_squared_error(y_test,pred))

MSE :  0.020688684556200737

In [61]:
new_pred = en_r.predict(pd.DataFrame([[11]], columns=["Study_Hours"]))

In [64]:
print(f"\nPredicted Exam Score  : {new_pred[0]:.0f}")

Predicted Exam Score  : 85

In [65]:
print(f"\nR2 score : {r2_score(y_test,pred):.2f}")

R2 score : 1.00